### ISSUE TITLE
Add RemarkHTML

### ISSUE THREAD

**Issue by Rokt33r** [Rokt33r/typed-remark#10]
To add RemarkHTML, we have to prepare its dependencies first.

- [x]  [mdast-util-to-hast](https://github.com/syntax-tree/mdast-util-to-hast)
  - [x] [collapse-white-space](https://github.com/wooorm/collapse-white-space) -> typed-string-utils
  - [x] [detab](https://github.com/wooorm/detab) -> typed-string-utils
  - [x] [mdurl](https://github.com/markdown-it/mdurl/blob/master/decode.js) considering to create type definitions rather than forking -> Reviewing now. https://github.com/DefinitelyTyped/DefinitelyTyped/pull/20581
  - [x] [trim-lines](https://github.com/wooorm/trim-lines) -> typed-string-utils, better to rename `collapseLines`
  - ~~[unist-util-generated](https://github.com/syntax-tree/unist-util-generated)~~ excluded
  - ~~[unist-util-position](https://github.com/syntax-tree/unist-util-position)~~ excluded
- ~~[commonmark.json](https://github.com/wooorm/commonmark.json) for testing~~
- [x] [hast-util-to-html](https://github.com/syntax-tree/hast-util-to-html)
  - [x] [hast-util-is-element](https://github.com/syntax-tree/hast-util-is-element) assigned to @rohjs 
  - [x] [hast-util-whitespace](https://github.com/syntax-tree/hast-util-whitespace) assigned to @rohjs 
  - [x] [property-information](https://github.com/wooorm/property-information) 
  - [x] [space-separated-tokens](https://github.com/wooorm/space-separated-tokens)
  - [x] [html-void-elements](https://github.com/wooorm/html-void-elements) assigned to @rohjs 
  - [x] [unist-util-is](https://github.com/syntax-tree/unist-util-is)
  - [x] [kebab-case](https://github.com/joakimbeng/kebab-case) -> typed-string-utils
  - [x] [ccount](https://github.com/wooorm/ccount/blob/master/index.js) -> typed-string-utils
- [x] [hast-util-sanitize](https://github.com/syntax-tree/hast-util-sanitize)

**Comment by rohjs** [comment]
👌👌 Roger that, sir

**Comment by Rokt33r** [comment]
@rohjs 
`html-void-elements` doesn't need any tests. After executed `npm run cp`, discard `jest.json` and fix scripts just like `character-entities`.
